/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'prashantchaudhary' at '10/4/16 10:12 PM' with Gradle 2.2.1
 *
 * @author prashantchaudhary, @date 10/4/16 10:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
